import { useQuery } from "@tanstack/react-query";
import "../style.scss";
import { UserEndpoint } from "../../../../api/endpoints/user.endpoint";
import { getUserPRofile } from "../../../../api/configs/user.config";
import { ChatItem } from "../../../../components/Chat/ChatItem";
import { ChatPanel } from "../../../../components/Chat/ChatPanel";

export const ProfileChat = () => {
  const {
    data: user,
    isLoading,
    refetch,
  } = useQuery({
    queryKey: [UserEndpoint.GET_USER_INFORMATION],
    queryFn: () => getUserPRofile(),
  });
  return (
    <div className="profile__chat">
      <div className="profile__chat-header">
        <h1>Tin nhắn</h1>
        <p>Tin nhắn của bạn.</p>
      </div>
      <div className="profile__chat-body">
        <div className="profile__chat-left">
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
            focus
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
          <ChatItem
            icon={user?.avatarUrl}
            name={user?.fullName}
            content={user?.email}
            time={user?.dateOfBirth}
            isRead={true}
          />
        </div>
        <div className="profile__chat-right">
          <ChatPanel />
        </div>
      </div>
    </div>
  );
};
